spring:
  application:
    name: SearchService
  datasource:
    metadata:
      url: ${POSTGRES_STREAMING_JDBC_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
    playlist:
      url: ${POSTGRES_PLAYLIST_JDBC_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
  elastic:
    url: ${ELASTICSEARCH_URL}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  debezium:
    url: ${DEBEZIUM_URL}
    request-body-path: classpath:init-scripts/debezium/*.json
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_REINDEX_BOOTSTRAP_SERVERS}
      trusted-packages: com.bush.search.event.kafka

server:
  port: 8082