spring:
  datasource:
    metadata:
      name: metadata_db
      username: postgres
      password: postgres
    playlist:
      name: playlist_db
      username: postgres
      password: postgres
  elastic:
    url: localhost:9200
    username: elastic
    password: elastic1
  debezium:
    url: http://localhost:8083
    request-body-path: classpath:init-scripts/debezium/*.json
  kafka:
    consumer:
      bootstrap-servers: localhost:9096
      trusted-packages: com.bush.search.event.kafka

server:
  port: 8082